#!/usr/bin/env node

/**
 * ATS Resume Optimizer - Setup Script
 *
 * Validates your Gemini API key, auto-detects the best available model,
 * and writes everything to .env so you can just run: npm run dev
 *
 * Usage:
 *   node setup.mjs                          # Interactive - prompts for API key
 *   GEMINI_API_KEY=xxx node setup.mjs       # Non-interactive
 *   node setup.mjs --model gemini-2.5-pro   # Override model selection
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import readline from "readline";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.join(__dirname, ".env");

// --- Model preference order (best flash model first) ---
const MODEL_PREFERENCE = [
  "gemini-2.5-flash",
  "gemini-2.0-flash",
  "gemini-1.5-flash",
];

// --- Helpers ---

function parseEnvFile() {
  const env = {};
  if (fs.existsSync(ENV_PATH)) {
    const lines = fs.readFileSync(ENV_PATH, "utf-8").split("\n");
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      env[key] = val;
    }
  }
  return env;
}

function writeEnvFile(env) {
  const lines = [
    "# ATS Resume Optimizer - Auto-generated by setup.mjs",
    "# Last updated: " + new Date().toISOString(),
    "",
  ];
  for (const [key, val] of Object.entries(env)) {
    lines.push(key + "=" + val);
  }
  lines.push("");
  fs.writeFileSync(ENV_PATH, lines.join("\n"), "utf-8");
}

function askQuestion(question) {
  var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise(function (resolve) {
    rl.question(question, function (answer) {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function log(icon, msg) {
  console.log("  " + icon + "  " + msg);
}

// --- API calls ---

async function listModels(apiKey) {
  var url =
    "https://generativelanguage.googleapis.com/v1beta/models?key=" +
    apiKey +
    "&pageSize=100";
  var res = await fetch(url);
  if (!res.ok) {
    var body = await res.text();
    throw new Error("API Error " + res.status + ": " + body);
  }
  var data = await res.json();
  return (data.models || []).map(function (m) {
    return m.name.replace("models/", "");
  });
}

async function testModel(apiKey, model) {
  var url =
    "https://generativelanguage.googleapis.com/v1beta/models/" +
    model +
    ":generateContent?key=" +
    apiKey;
  var res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: "Respond with only: OK" }] }],
      generationConfig: { maxOutputTokens: 10 },
    }),
  });
  return res.ok;
}

function pickBestModel(available) {
  for (var i = 0; i < MODEL_PREFERENCE.length; i++) {
    if (available.includes(MODEL_PREFERENCE[i])) {
      return MODEL_PREFERENCE[i];
    }
  }
  // Fallback: find any flash model that supports generateContent
  var flashModels = available.filter(function (m) {
    return (
      m.includes("flash") &&
      !m.includes("live") &&
      !m.includes("lite") &&
      !m.includes("image") &&
      !m.includes("embedding")
    );
  });
  if (flashModels.length > 0) return flashModels[0];
  return null;
}

// --- Main ---

async function main() {
  console.log("");
  console.log("  +----------------------------------------------+");
  console.log("  |     ATS Resume Optimizer - Setup              |");
  console.log("  +----------------------------------------------+");
  console.log("");

  // 1. Parse CLI args for --model override
  var args = process.argv.slice(2);
  var modelOverride = null;
  var modelIdx = args.indexOf("--model");
  if (modelIdx !== -1 && args[modelIdx + 1]) {
    modelOverride = args[modelIdx + 1];
  }

  // 2. Get API key: CLI env > existing .env > prompt
  var existingEnv = parseEnvFile();
  var apiKey = process.env.GEMINI_API_KEY || existingEnv.GEMINI_API_KEY || "";

  if (!apiKey) {
    apiKey = await askQuestion("  Enter your Gemini API key: ");
  }

  if (!apiKey) {
    log("[X]", "No API key provided. Exiting.");
    process.exit(1);
  }

  // 3. Validate key by listing models
  log("[*]", "Validating API key...");
  var availableModels;
  try {
    availableModels = await listModels(apiKey);
  } catch (err) {
    log("[X]", "API key validation failed: " + err.message);
    log("[!]", "Get a key at: https://aistudio.google.com/apikey");
    process.exit(1);
  }
  log("[OK]", "API key valid - " + availableModels.length + " models available");

  // 4. Select model
  var selectedModel;
  if (modelOverride) {
    if (availableModels.includes(modelOverride)) {
      selectedModel = modelOverride;
      log("[>]", "Using specified model: " + selectedModel);
    } else {
      log("[!]", 'Model "' + modelOverride + '" not found in your account.');
      var flashList = availableModels
        .filter(function (m) {
          return m.includes("flash");
        })
        .join(", ");
      log("[i]", "Available flash models: " + flashList);
      process.exit(1);
    }
  } else {
    log("[*]", "Auto-detecting best available model...");
    selectedModel = pickBestModel(availableModels);
    if (!selectedModel) {
      log("[X]", "No compatible Gemini Flash model found on your account.");
      log("[i]", "Available: " + availableModels.slice(0, 15).join(", ") + "...");
      process.exit(1);
    }
    log("[OK]", "Best model detected: " + selectedModel);
  }

  // 5. Quick smoke test
  log("[*]", "Testing " + selectedModel + " with a quick API call...");
  var works = await testModel(apiKey, selectedModel);
  if (works) {
    log("[OK]", "Model responded successfully!");
  } else {
    log("[!]", 'Model "' + selectedModel + '" did not respond. It may require billing or have been deprecated.');
    var proceed = await askQuestion("  Continue anyway? (y/N): ");
    if (proceed.toLowerCase() !== "y") {
      process.exit(1);
    }
  }

  // 6. Write .env
  var newEnv = Object.assign({}, existingEnv, {
    GEMINI_API_KEY: apiKey,
    GEMINI_MODEL: selectedModel,
  });
  writeEnvFile(newEnv);

  console.log("");
  log("[OK]", "Setup complete! Your .env file:");
  console.log("");
  console.log(
    "      GEMINI_API_KEY = " +
      apiKey.slice(0, 8) +
      "..." +
      apiKey.slice(-4)
  );
  console.log("      GEMINI_MODEL   = " + selectedModel);
  console.log("");
  log("-->", "Run the app with: npm run dev");
  console.log("");
}

main().catch(function (err) {
  console.error("Setup failed:", err);
  process.exit(1);
});
